#version 450 core

layout(local_size_x=1,local_size_y=1,local_size_z=1) in;

layout(std430, binding=0) buffer sPositions {
	vec4 positions[];
};

layout(std430, binding=1) buffer sVelocities {
	vec4 velocities[];
};

#include "uTime.h"
#include "uSceneWalls.h"

void main() {
//	for (int i = 0; i  < walls.length(); ++i) {
//		velocities[gl_GlobalInvocationID.x] += 1/(positions[gl_GlobalInvocationID.x] - walls[i]);
//	}
	positions[gl_GlobalInvocationID.x] += velocities[gl_GlobalInvocationID.x];
}